addSbtPlugin("org.scalameta"             % "sbt-mdoc"     % "2.3.2")
addSbtPlugin("com.eed3si9n"              % "sbt-unidoc"   % "0.4.3")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.3.3")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt" % "2.4.6")
addSbtPlugin("com.codecommit" % "sbt-github-packages" % "0.5.3")
