name: CI

on:
  pull_request:
  push:
    branches: ['master']
  # release:
  #   types:
  #     - published

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        java: ['openjdk@1.17.0']
        scala: ['2.13.9', '3.2.0']
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: ${{ matrix.java }}
    - name: Cache scala dependencies
      uses: coursier/cache-action@v5
    - name: Lint code
      run: sbt check
    - name: Run tests
      run: sbt ++${{ matrix.scala }} test